artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: shanegerami/ai-vs-human-text
  local_data_file: artifacts/data_ingestion/Dataset.zip
  unzip_dir: artifacts/data_ingestion

data_clean:
  root_dir: artifacts/data_clean
  source_dir: artifacts/data_ingestion/AI_Human.csv
  final_dir: artifacts/data_clean/data_clean.csv